version: '3'

services:
  app:
    build: .
    command: bash -c "npm run start:dev"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      TZ: 'Asia/Tokyo'
