on:
  schedule:
    - cron: 0 0 * * 7
name: actions-package-update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@0.5.0
      env:
        AUTHOR_EMAIL: tazitaziawawa@gmail.com
        AUTHOR_NAME: samuraikun
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPDATE_COMMAND: npm
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
